## Cyclistic Bike Share Analysis

### Project Overview

This project analyzes bike-share trip data to identify usage patterns and compare member and casual riders.

## Objective
  -To study how casual riders and annual members use Cyclistic bikes differently.
  -To gain any other useful insights for designing new marketing strategies.

import pandas as pd

In [3]:
df = pd.read_excel("2020_cyclists.xlsx")

In [16]:
df = df.reset_index(drop=True)

df.info()

In [9]:
for col in df.columns:
    types = df[col].apply(type).value_counts()
    if len(types) > 1:
        print(f"Column: {col}")
        print(types)

Column: ride_id
ride_id
<class 'str'>    420509
<class 'int'>       277
Name: count, dtype: int64

In [6]:
df.isnull().sum()

ride_id               0
started_at            0
ended_at              0
start_station_name    0
end_station_name      0
member_casual         0
ride_length           0
day of week           0
Hour                  0
Route                 0
dtype: int64

In [6]:
df[df.duplicated()]

Empty DataFrame
Columns: [ride_id, started_at, ended_at, start_station_name, end_station_name, member_casual, ride_length, day of week, Hour, Route]
Index: []

In [7]:
df["member_casual"].value_counts()

member_casual
member    375993
casual     44793
Name: count, dtype: int64

In [7]:
df["member_casual"].value_counts(normalize=True).mul(100).round(2)

member_casual
member    89.35
casual    10.65
Name: proportion, dtype: float64

In [14]:
df = df[df["ride_length"] <= pd.Timedelta(days=1)]

In [4]:
df["ride_length"].dtype

dtype('float64')

In [9]:
df["ride_length"] = pd.to_timedelta(df["ride_length"], unit="D")

In [27]:
df["ride_length"].head(5)

0   0 days 00:08:00
1   0 days 00:04:00
2   0 days 00:03:00
3   0 days 00:08:00
4   0 days 00:05:00
Name: ride_length, dtype: timedelta64[ns]

In [11]:
df[df["ride_length"] <= pd.Timedelta(0)]

Empty DataFrame
Columns: [ride_id, started_at, ended_at, start_station_name, end_station_name, member_casual, ride_length, day of week, Hour, Route]
Index: []

In [18]:
df["ride_length"].mean().round("s")

Timedelta('0 days 00:14:35')

In [19]:
long_rides = df[df["ride_length"] > pd.Timedelta(days=1)]

print(len(long_rides))
print(round(len(long_rides) / len(df) * 100, 3))

0
0.0

In [21]:
df.groupby("member_casual")["ride_length"].mean().round("s")

member_casual
casual   0 days 00:39:55
member   0 days 00:11:34
Name: ride_length, dtype: timedelta64[ns]

In [22]:
df["start_station_name"].value_counts().head(10)

start_station_name
Canal St & Adams St             7781
Clinton St & Madison St         6755
Clinton St & Washington Blvd    5911
Kingsbury St & Kinzie St        4600
Columbus Dr & Randolph St       4390
Franklin St & Monroe St         3686
Canal St & Madison St           3606
Clinton St & Lake St            3565
Larrabee St & Kingsbury St      3536
Michigan Ave & Washington St    3524
Name: count, dtype: int64

In [25]:
df["Route"].value_counts().head(5)

Route
Ellis Ave & 60th St → University Ave & 57th St                 478
Lake Shore Dr & Monroe St → Lake Shore Dr & Monroe St          456
Canal St & Adams St → Michigan Ave & Washington St             455
Michigan Ave & Washington St → Clinton St & Washington Blvd    453
University Ave & 57th St → Ellis Ave & 60th St                 421
Name: count, dtype: int64

In [26]:
df["day of week"].value_counts()

day of week
3    73896
4    68782
2    65290
5    65031
6    59752
1    50441
7    37304
Name: count, dtype: int64

In [28]:
df.groupby("day of week")["ride_length"].mean().round('s').sort_values(ascending=False)
#weedend has average longer rides

day of week
1   0 days 00:22:07
7   0 days 00:17:47
4   0 days 00:13:45
6   0 days 00:13:20
3   0 days 00:12:52
5   0 days 00:12:51
2   0 days 00:12:34
Name: ride_length, dtype: timedelta64[ns]

In [58]:
df.groupby("day of week")["member_casual"].value_counts()
#sunday has high number of casual riders compared to other days and make sunday has the highest average ride_length.

day of week  member_casual
1            member           35659
             casual           14782
2            member           61558
             casual            3732
3            member           69304
             casual            4592
4            member           63596
             casual            5186
5            member           60820
             casual            4211
6            member           55126
             casual            4626
7            member           29867
             casual            7437
Name: count, dtype: int64

In [33]:
df[df["day of week"] == 1]["ride_length"].describe()

count                        50441
mean     0 days 00:22:07.355920778
std      0 days 00:42:51.825390996
min      0 days 00:00:59.999999996
25%      0 days 00:06:59.999999999
50%      0 days 00:13:00.000000001
75%      0 days 00:24:59.999999999
max                0 days 22:41:00
Name: ride_length, dtype: object

In [35]:
df["end_station_name"].apply(type).value_counts()

end_station_name
<class 'str'>    420496
Name: count, dtype: int64

In [24]:
df.sort_values(by="ride_length", ascending=False).head(5)

,ride_id,started_at,ended_at,start_station_name,end_station_name,member_casual,ride_length,day of week,Hour,Route
259227,EB83072244DF5183,2020-02-12 11:27:00,2020-02-13 11:22:00,Clark St & Drummond Pl,Millennium Park,casual,0 days 23:55:00.000000001,4,11,Clark St & Drummond Pl → Millennium Park
203761,EB48B0C5B8A7E284,2020-02-14 17:52:00,2020-02-15 17:45:00,Dearborn St & Monroe St,Michigan Ave & 14th St,member,0 days 23:53:00,6,17,Dearborn St & Monroe St → Michigan Ave & 14th St
331812,1924EA914F6FC007,2020-03-13 18:08:00,2020-03-14 18:01:00,Federal St & Polk St,Field Blvd & South Water St,casual,0 days 23:53:00,6,18,Federal St & Polk St → Field Blvd & South Wate...
119802,D77022E99184DCFC,2020-01-29 10:16:00,2020-01-30 10:04:00,Michigan Ave & Pearson St,Wabash Ave & Grand Ave,casual,0 days 23:48:00.000000002,4,10,Michigan Ave & Pearson St → Wabash Ave & Grand...
301721,0EE1ADD10A6B94A9,2020-03-05 07:47:00,2020-03-06 07:29:00,Racine Ave & Fullerton Ave,Clifton Ave & Armitage Ave,member,0 days 23:42:00,5,7,Racine Ave & Fullerton Ave → Clifton Ave & Arm...

In [28]:
df["ride_length"].quantile(0.99).round("s")

Timedelta('0 days 01:23:00')

In [15]:
df["ride_length"].quantile([0.99, 0.995, 0.999]).round("s")

0.990   0 days 01:23:00
0.995   0 days 02:02:00
0.999   0 days 08:37:30
Name: ride_length, dtype: timedelta64[ns]

In [23]:
df["Hour"].value_counts().head(6)

Hour
17    52549
16    44431
8     42374
7     32224
18    30846
15    28037
Name: count, dtype: int64

In [38]:
df.sort_values(by="ride_length", ascending=False).head(5)

,ride_id,started_at,ended_at,start_station_name,end_station_name,member_casual,ride_length,day of week,Hour,Route
259227,EB83072244DF5183,2020-02-12 11:27:00,2020-02-13 11:22:00,Clark St & Drummond Pl,Millennium Park,casual,0 days 23:55:00.000000001,4,11,Clark St & Drummond Pl → Millennium Park
203761,EB48B0C5B8A7E284,2020-02-14 17:52:00,2020-02-15 17:45:00,Dearborn St & Monroe St,Michigan Ave & 14th St,member,0 days 23:53:00,6,17,Dearborn St & Monroe St → Michigan Ave & 14th St
331812,1924EA914F6FC007,2020-03-13 18:08:00,2020-03-14 18:01:00,Federal St & Polk St,Field Blvd & South Water St,casual,0 days 23:53:00,6,18,Federal St & Polk St → Field Blvd & South Wate...
119802,D77022E99184DCFC,2020-01-29 10:16:00,2020-01-30 10:04:00,Michigan Ave & Pearson St,Wabash Ave & Grand Ave,casual,0 days 23:48:00.000000002,4,10,Michigan Ave & Pearson St → Wabash Ave & Grand...
301721,0EE1ADD10A6B94A9,2020-03-05 07:47:00,2020-03-06 07:29:00,Racine Ave & Fullerton Ave,Clifton Ave & Armitage Ave,member,0 days 23:42:00,5,7,Racine Ave & Fullerton Ave → Clifton Ave & Arm...

In [40]:
df.sort_values(by="ride_length").head(5)

,ride_id,started_at,ended_at,start_station_name,end_station_name,member_casual,ride_length,day of week,Hour,Route
269781,82134B22A0E73599,2020-02-29 07:12:00,2020-02-29 07:13:00,Wells St & Walton St,Wells St & Elm St,member,0 days 00:00:59.999999996,7,7,Wells St & Walton St → Wells St & Elm St
265589,A9033C2432C5025A,2020-02-27 18:37:00,2020-02-27 18:38:00,Broadway & Berwyn Ave,Broadway & Berwyn Ave,member,0 days 00:00:59.999999996,5,18,Broadway & Berwyn Ave → Broadway & Berwyn Ave
16090,2CFA1A1C41FC6F51,2020-01-26 13:12:00,2020-01-26 13:13:00,Smith Park (*),Smith Park (*),casual,0 days 00:00:59.999999996,1,13,Smith Park (*) → Smith Park (*)
166541,39D1D9519999A06F,2020-02-13 19:08:00,2020-02-13 19:09:00,Dearborn St & Monroe St,Dearborn St & Monroe St,member,0 days 00:00:59.999999996,5,19,Dearborn St & Monroe St → Dearborn St & Monroe St
300105,622CA6EC770465B7,2020-03-06 17:16:00,2020-03-06 17:17:00,Halsted St & Archer Ave,Emerald Ave & 28th St,member,0 days 00:00:59.999999996,6,17,Halsted St & Archer Ave → Emerald Ave & 28th St

In [45]:
df["ride_length"].value_counts().head(10)

ride_length
0 days 00:04:59.999999998    33736
0 days 00:06:00.000000002    32353
0 days 00:04:00.000000001    30794
0 days 00:06:59.999999999    29962
0 days 00:08:00.000000003    27128
0 days 00:09:00              24530
0 days 00:02:59.999999997    22927
0 days 00:09:59.999999996    21709
0 days 00:11:00              18799
0 days 00:11:59.999999997    16501
Name: count, dtype: int64

In [43]:
df["start_station_name"].apply(type).value_counts()

start_station_name
<class 'str'>    420496
Name: count, dtype: int64

In [44]:
df[~df["start_station_name"].apply(lambda x: isinstance(x, str))]

Empty DataFrame
Columns: [ride_id, started_at, ended_at, start_station_name, end_station_name, member_casual, ride_length, day of week, Hour, Route]
Index: []

In [46]:
df["started_at"].apply(type).value_counts()

started_at
<class 'pandas._libs.tslibs.timestamps.Timestamp'>    420496
Name: count, dtype: int64

In [62]:
df.groupby(df["started_at"].dt.date).size()

started_at
2020-01-01    2122
2020-01-02    6443
2020-01-03    5866
2020-01-04    3167
2020-01-05    3010
              ...
2020-03-27    1477
2020-03-28    1433
2020-03-29    1435
2020-03-30    1918
2020-03-31    1610
Length: 91, dtype: int64

In [67]:
df["month"] = df["started_at"].dt.month
df["day_name"] = df["started_at"].dt.day_name()
df["start_hour"] = df["started_at"].dt.hour

In [70]:
pivot = pd.pivot_table(
    df,
    index="start_hour",
    columns="day_name",
    values="ride_id",
    aggfunc="count"
)
pivot

day_name    Friday  Monday  Saturday  Sunday  Thursday  Tuesday  Wednesday
start_hour
0              240     206       327     460       167      131        180
1              117     106       221     305       101       60        143
2               75      74       128     174        57       45         96
3               59      67        91     119        58       36         44
4              145     217        66      72       179      228        175
5              907    1040       159     128       938     1094       1014
6             2510    2806       326     268      2828     3350       3015
7             5483    6024       768     528      5983     7165       6273
8             6935    8089      1379    1070      7629     9087       8185
9             3070    3193      1888    1747      3154     3518       3409
10            1854    1997      2560    2678      1809     1796       1860
11            2403    2246      3182    3802      2095     2394       2393
12            2793    2611      3462    4755      2510     2924       2842
13            2959    2500      3696    5522      2360     2812       2863
14            2932    2301      3748    5866      2277     2582       2728
15            4154    3448      3516    5783      3473     3956       3707
16            6792    6875      3084    5288      7060     8051       7281
17            7245    9121      2537    4152      9251    10551       9692
18            3825    5396      1898    2822      5328     6149       5428
19            2103    3124      1348    1760      3228     3489       3173
20            1204    1737       933    1145      1916     1988       1823
21             898    1187       793    1030      1354     1396       1311
22             633     632       682     578       821      737        758
23             416     293       512     389       455      357        389